# Generated by Django 3.2.16 on 2023-01-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(verbose_name='应用')),
                ('domain', models.IntegerField(verbose_name='业务')),
                ('hostname', models.CharField(max_length=128, verbose_name='地址')),
                ('label', models.CharField(max_length=64, verbose_name='标签')),
                ('cpu', models.FloatField(default=0.0, verbose_name='CPU')),
                ('disk', models.FloatField(default=0.0, verbose_name='DISK')),
                ('memory', models.FloatField(default=0.0, verbose_name='MEM')),
                ('enabled', models.CharField(choices=[('0', '不可用'), ('1', '可用'), ('2', '禁用')], default='0', max_length=2, verbose_name='状态')),
                ('alive_account_count', models.IntegerField(default=0, verbose_name='可用账号')),
                ('pending_task_count', models.IntegerField(default=0, verbose_name='待执行任务')),
                ('accounts', models.TextField(blank=True, null=True, verbose_name='账号统计详情')),
                ('tasks', models.TextField(blank=True, null=True, verbose_name='任务统计详情')),
                ('updated_ts', models.IntegerField(default=0, verbose_name='更新时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
                'db_table': 'online_machine',
            },
        ),
    ]
